YAP-509 Ошибка сервера, если не корректный телефон
sushi-market/laravel-uds-sdk pull request #13
Opened 2024-08-28 10:37 UTC by Gleb-Shalygin

Pull request created in: https://jira.sushi-market.dev/browse/YAP-509

2024-08-30 12:54 UTC, Nikolay-Mininskiy requested changes

2024-08-30 12:54 UTC, Nikolay-Mininskiy commented on src/Services/HttpClientProduction.php
> +use SushiMarket\UdsSdk\Exceptions\ParticipantIsBlockedException;
Undefined class 'ParticipantIsBlockedException'

2024-09-06 04:12 UTC, Nikolay-Mininskiy requested changes

2024-09-06 04:12 UTC, Nikolay-Mininskiy commented on src/Exceptions/ParticipantIsBlockedException.php
> +
Добавь declare(strict_types=1);
Сейчас это во всех файлах используется

2024-09-30 11:51 UTC, m0nclous commented
Допишите тесты на новую функциональность

2024-10-11 11:50 UTC, Nikolay-Mininskiy requested changes

2024-10-11 11:50 UTC, Nikolay-Mininskiy commented on src/Services/HttpClientFake.php
> +    static function fakeParticipantIsBlocked(): string
переименуй в `fakeParticipantIsBlockedResponse`
как в других подобных методах, возвращающих тело ответа

2024-10-11 11:50 UTC, Nikolay-Mininskiy commented on tests/CreateTransactionTest.php
> +    public function test_participant_is_blocked()
переименуй в `test_participant_is_blocked_exception`
как в других методах, тестирующих исключения

2025-04-09 13:04 UTC, closed without merging